### ISSUE TITLE
FEC ID mixup

### ISSUE THREAD

**Issue by mrumsky** [unitedstates/congress-legislators#247]
I found a couple issues in legislators_historical.yaml:

1. Trent Lott has no FEC ID. It should be S8MS00162.
2. Trent Lott's FEC ID (S8MS00162) is incorrectly assigned to Blanche Lincoln, whose FEC IDs should be S8AR00112, H2AR01022.

Thanks!

**Comment by JoshData** [comment]
@handlers - This is more Sunlight's department. Want to look into it?

@mrumsky Thanks for posting here.

**Comment by kentr** [comment]
@handlers - I'm working with @mrumsky on the FEC IDs on our end.  

We're considering submitting a patch / change suggestion, but wanted to know the scope of the fix.  Is the problem something that could be fixed with a SQL statement?  Or is it in the scraper code?  Or something else?

Thanks

**Comment by handlers** [comment]
Sorry this slipped — I'm seeing the same inaccuracy as you. Thanks so much for reporting it. All you need to do is submit a pull request with the appropriate lines updated in `legislators-historical.yaml`! If you package into a PR, I would ping @jsfenfen in a comment, since he knows a ton about FEC IDs.
