### ISSUE TITLE
Data Validity

### ISSUE THREAD

**Issue by gmj2053** [unitedstates/congress-legislators#277]
Hi, we are hoping to use your data to manage our congressional web archiving activity at the Library of Congress.  We used govtrack last year to try to keep up with the social media sites for the US Congressional members.  We are integrating this output with our database right now.  Just curious about the validity of data, for example, noticed that Joe Lieberman isn't on https://raw.githubusercontent.com/unitedstates/congress-legislators/master/legislators-current.yaml
and Schock and Nunnelee missing datapoints.

**Comment by dwillis** [comment]
Hi Gina,

That's because the file you point to is of currently-serving legislators, so it wouldn't include Lieberman, Schock or Nunnelee, since none of them are currently serving. You can find them (and the rest) in our [historical legislators file](https://github.com/unitedstates/congress-legislators/blob/master/legislators-historical.yaml).

**Comment by gmj2053** [comment]
Thanks, some how I thought I saw some retired legislators, but we don't need those, so this file is good.  Keep up the good work!
