### ISSUE TITLE
.NET Client Library

### ISSUE THREAD

**Issue by mekinney** [unitedstates/congress-legislators#311]
Hello everyone.  I've been playing with this API as part of a learning project and there is a ton of great information.  Thank you for creating it.

I'm now working with .NET and am wondering if there is a .NET Client Library that someone has started or looked into.  If not, it may be something I can contribute back if it would be useful.

Thoughts appreciated on the general usefulness of a .NET Client Library and any existing projects that may help create one.

Thanks in advance,
Mike

**Comment by konklone** [comment]
Hey @mekinney, thanks for the kind words! I'm not aware of any .NET client libraries for our dataset, or any specific .NET uses, but since it's a bulk dataset and not an API we don't know most of the uses people find for our data. Client libraries for a bulk dataset are less common than for a live API, but if you do make one, please let us know and we'd be happy to link to it in our README.

**Comment by mekinney** [comment]
FYI, I'm still slowly working on this, and have it mostly done.  It's interesting making a type safe version that requires me review nearly every returned property to understand what it is.  I'll pop it up on GitHub when it gets more presentable.

**Comment by joelcollinsdc** [comment]
@mekinney Please let us know if its finished so we can add a link in the README.  Please open a new issue when you are ready.
