### ISSUE TITLE
yaml vs. json speed

### ISSUE THREAD

**Issue by jonathanstrong** [unitedstates/congress-legislators#362]
Is there any reason to use yaml for the serialization format? It's super slow. I just installed the C LibYAML bindings and it's still taking my machine ~14 seconds to load legislators-historical.yaml. By contrast if I save the data in json it takes 375ms to open.

**Comment by dwillis** [comment]
Yes, that's the reason. I don't think we envisioned this file as being loaded on the fly by web requests, for example, but rather one that was periodically updated and stored.

**Comment by jonathanstrong** [comment]
makes sense, and yaml is good for that reason. just find it annoying when I go to parse it. thanks!

**Comment by Hardmath123** [comment]
Would a JSON mirror help? The YAML can be serialized easily to JSON, so a git hook that makes JSON copies wouldn't be hard to do. It can live in the gh-pages branch so that people can query the JSON as a web API.

**Comment by schmod** [comment]
The `git blame` is also a lot cleaner with YAML, because commas don't need to be inserted.

**Comment by AlJohri** [comment]
for usage, I just convert to JSON first:

```
yaml2json <(curl -s https://raw.githubusercontent.com/unitedstates/congress-legislators/master/legislators-current.yaml 2>&1) | jsonpp >legislators-current.json
```

requirements
```
npm install -g yamljs
brew install jsonpp
```

**Comment by hboylan** [comment]
I'm using the same yamljs package as @AlJohri.

Unfortunately, it's unable to parse multiline strings like in [committees-current.yaml](https://github.com/unitedstates/congress-legislators/blob/master/committees-current.yaml#L36). 

For now, I have a script to condense multilines into one, but since the YAML should be both human-readable and machine-parseable the correct solution is to add a [multiline indicator](https://gist.github.com/rjattrill/7523554).

**Comment by JoshData** [comment]
I think our file conforms to the YAML specification.

**Comment by joshbetz** [comment]
JSON serialization is also built into most modern programming languages, while YAML is not.

**Comment by essandess** [comment]
+1 to keep YAML as a raw format for ease of editing and correcting.

Also +1 to mirror a json for application speed because the YAML load time is ridiculously slow.

I've seen this myself with this lookup script [congress_lookup.py](../../../essandess/congress-legislators/blob/master/scripts/congress_lookup.py) to access contact information in the database discussed in #343.

**Comment by essandess** [comment]
YAML load speeds are improved by 10x if the fast C Loader is used:

```python
%timeit y = open('legislators-current.yaml','r'); foo = yaml.load(y)
1 loop, best of 3: 7.96 s per loop

%timeit y = open('legislators-current.yaml','r'); foo = yaml.load(y, Loader=yaml.CLoader)
1 loop, best of 3: 976 ms per loop
```

I've updated my own [lookup code](../../../essandess/congress-legislators/blob/master/scripts/congress_lookup.py) to use this option.

**Comment by konklone** [comment]
This is a common request, and since we are pretty good about using `utils` functions (`save_data`, `load_data`) instead of doing direct YAML calls inside our gathering scripts, we could very easily add a hook to `save_data` that writes out the equivalent JSON version. It wouldn't change how our data gathering scripts work at all.

So :+1: from me for this, and let me know how I can help.

**Comment by konklone** [comment]
@essandess The link to your revised lookup code is a 404 now -- any way I can see that? If it's just a matter of swapping in the C-based loader, that seems like an all-upside improvement for us.

**Comment by mininternet** [comment]
+1 to write out data to JSON

**Comment by essandess** [comment]
@konklone Thanks, I fixed the link. The lookup script was moved up one directory based on feedback in the PR.

**Comment by essandess** [comment]
Another benefit of auto-generation of JSON is that no non-native yaml module dependencies would be required—the json module comes bundled with basic Python installs.

**Comment by mininternet** [comment]
Another issue with YAML is that committee descriptions cause errors when converting to JSON, due to line breaks, so JSON output would be especially helpful in this regard.

**Comment by hboylan** [comment]
This issue is no longer just about speed.

Many of us use NodeJS which requires us to convert YAML to JSON. Unfortunately, this isn't possible for some files due to the line breaks as some of us have [mentioned](https://github.com/unitedstates/congress-legislators/issues/362#issuecomment-246191154).

**Comment by joelcollinsdc** [comment]
Is the json that is currently generated when running alternative_formats.py sufficient?  And the problem is that people are just downloading the file / repo directly so its not convenient to run a python script to get the json right?

Short of adding a one liner to save_data to also save the json, what else would be needed for this?  A travis command to make sure that someone didn't hand edit the yaml and forget to regenerate json would be good right?  I can't seem to find a way to get github to not show the diffs for these files.  Would screwing around with gitattributes to hide the json diffs be possible or helpful?
