### ISSUE TITLE
congress_lookup.py and python3?  How to install?

### ISSUE THREAD

**Issue by joelcollinsdc** [unitedstates/congress-legislators#437]
When trying to install urllib2 I get Collecting urllib2
  Could not find a version that satisfies the requirement urllib2 (from versions: )
No matching distribution found for urllib2

I have to say, while I really like the idea of collecting scripts like this, I wish this wasn't part of this repo.  The script itself allows you to load the data over a URL (--download), right?  So you could use the script without needing the rest of the repo?  It almost seems like a step backwards to include this script in the repo then instead of letting it stand on its own.

In an unrelated note, i've been using the requests module but never put it in requirements.txt... it would be good to standardize on one though.

cc @essandess

**Comment by konklone** [comment]
@essandess Would you be up for providing clear run-this-script-from-a-clean-slate instructions, that you've verified work?

@joelcollinsdc The `--download` flag is a remnant from when it wasn't in the repo. It could probably be dropped, but I'm not going to nitpick the script contents if it's providing a function. Is it getting in your way?

**Comment by joelcollinsdc** [comment]
I'm definitely not trying to criticize the script, I was actually trying to use it to test the committee membership stuff.  I was thinking that since the script is able to run on its own, either using --data-dir or --download, it makes sense to me that some people would find it easier to just download the congress_lookup script and the script itself would maintain downloading/updating the right files for querying.

Either way... not criticizing.

**Comment by essandess** [comment]
@joelcollinsdc @konklone 

Both your questions a pertinent to a larger issue I'd like to address. One at a time,

- Re `urliib2`: This is a standard Python [library](https://docs.python.org/2/library/urllib2.html) that I've always seen come preinstalled with Python. If you don't have it, you can easily install it with `pip install urllib2` or anaconda, or some other favorite Python package manager. I like pip. Others like anaconda.

Perhaps `requests` could be a replacement, but there's a bigger issue: if you don't have `urllib2`, I'll bet you don't have the nonstandard `yaml` library, which is obviously essential here. `pip install` or anaconda to get this.

In all situations like this, the solution is to use your Python package manager, or change libraries.

- Re the `--download` flag: My intention here is so that the script can be used freely by anyone who doesn't know what `git clone` means. This would be a nice feature to exchange a python file for users who know enough to run a command line script, but not enough to clone a repo.

Right now, this functionality is of limited utility because such users would have to know about `pip install` or anaconda to get this working.

If, at some near-term future, the idea discussed in #362 of auto-generating json files from the yaml is implemented, then the standard `json` python library could be used instead, and the script would work as a standalone with `--download` on a lot of boxes without the git repo.

If this happens, I'd argue to make `--download` the default setting.

**Comment by essandess** [comment]
@joelcollinsdc PR #438 will fix this. You still must install the `yaml` library with pip or anaconda.

**Comment by joelcollinsdc** [comment]
thanks all.

i've been trying to figure out how to create a mirror of just the data files from this repo with all the alternative formats (json & csv) generated.  I'm stuck right now trying to figure out how to run git commands in aws lambda, but however it happens if its in this repo or in another one at some point there will be json files so this script could be run without pip.

I'll add a note to use urllib instead of requests for my stuff from now on.

**Comment by konklone** [comment]
@joelcollinsdc Instead of having a separate process do the transform from YAML -> JSON/CSV, how about we rewrite `utils.save_data()` to save in all formats simultaneously? That way it always happens, without any external infrastructure needed. Saving will be a bit slower, but seems well worth it.

**Comment by joelcollinsdc** [comment]
@konklone That would certainly be the easiest way to do it, which also probably means it's the right way to do it.  I'm partially looking into lambda or whatever just for learning purposes, but I could see a setup like that having lots of benefits:

- someone could watch a repo just for data changes, not for code changes or issues
- commit diffs stay a bit cleaner because they only have the yaml changes
- with a similar setup, future automation of other things becomes easier, like running committee_memberships.py and generating PR's on a schedule.

**Comment by konklone** [comment]
The third one is the most compelling to me, getting something like that set up would be very helpful. But it also would be infrastructure that someone has to own and pay for, and while that's welcome, I don't know if we want to make the existence of specific key files that we would publish and which downstream users would consume totally contingent on that infrastructure.
