### ISSUE TITLE
Social media to mimic legislators-historical.yaml

### ISSUE THREAD

**Issue by pullyl** [unitedstates/congress-legislators#462]
Has there been discussion of creating a mirror to legislators-historical with social media accounts?  One use case I am looking at is pulling tweets about ObamaCare while officials were serving.  For people who have been in office for several terms this is straightforward, but I lose elected officials for people who served in 2010 but no longer serve.  Definitely some question about the "officialness" of an account if it exists beyond a term, and might have to make some calls on a case by case basis.

Happy to do the leg work here if this data would be useful to people!

**Comment by JoshData** [comment]
I think we discussed this early on and decided that the git history would be good enough to track down old accounts.

I'd be ok revisiting this if we're talking about archiving the ID of the last known official account, since the data should not change much once it's put in. Especially if we use Twitter account numbers instead of screen names.

**Comment by pullyl** [comment]
Cool, thanks for the context.  Let me do some thinking on this.  If anyone else is also interested in consuming this data let me know!

**Comment by pullyl** [comment]
Looked into making these changes, but am finding (at least on twitter which is what I was most interested in) that the accounts have been deleted meaning I can't get the data that I am interested in.  Closing this issue for now, but if others have ideas about this would love to chat!
