### ISSUE TITLE
Best way to add executive branch twitter (and other social) accounts?

### ISSUE THREAD

**Issue by joeuelk** [unitedstates/congress-legislators#604]
What's the best way add these?

VP
@mike_pence

PREZ
@potus
@realDonaldTrump

Thank you

**Comment by JoshData** [comment]
Hi there. We don't have a place to put social media accounts for people other than legislators. And because we have a strict rule that the social media accounts that we include be ones run by legislative staff (not campaigns) it might be difficult to apply the same rules to other elected officials because the division between campaigns and official public relations isn't usually as clear. (For instance, Trump has claimed in court that his personal account is not an official account.)

On September 14, 2018 12:12:17 AM EDT, joeuelk <notifications@github.com> wrote:
>What's the best way add these?
>
>VP
>@mike_pence
>
>PREZ
>@potus
>@realDonaldTrump
>
>Thank you
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/unitedstates/congress-legislators/issues/604

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
