### ISSUE TITLE
Campaign twitter accounts

### ISSUE THREAD

**Issue by harrislapiroff** [unitedstates/congress-legislators#613]
I noticed that you explicitly only include government office accounts in your data. Is there any interest or openness to including campaign or personal accounts as well?

I'm working on a project analyzing content of representatives tweets using your data and I think it would be interesting to also have access to their campaign accounts' data, but I haven't found a good source for that yet.

**Comment by JoshData** [comment]
Hi.

I think we'd be fine including additional data in a separate file or in another repository in this organization, but the hard work will be collecting the data. So that we don't put the cart before the horse, I think it'd be best to postpone your question until after there's at least a preliminary database of campaign accounts.

I'm fine keeping this issue open indefinitely for others to weigh in on their interest in collecting the data, etc.

**Comment by harrislapiroff** [comment]
I'd be interested in contributing to the data collection effort if it would be well received.

**Comment by frisch1** [comment]
Here's the social media for campaigns, but just for the freshmen and new Senators,
[116th.xlsx](https://github.com/unitedstates/congress-legislators/files/2711662/116th.xlsx)

**Comment by dwillis** [comment]
I think we (the folks who run Politwoops) would be interested in providing an initial data set of congressional campaign accounts if that would be useful and propel this forward.

**Comment by dwillis** [comment]
We (ProPublica) now provide a dump of accounts being tracked by Politwoops, our deleted tweets site. https://www.propublica.org/datastore/dataset/politicians-tracked-by-politwoops

**Comment by jsfenfen** [comment]
Heyo @dwillis I noticed congressman-elect Ronny Jackson says he's on parler. Not following closely enough to know if there's a good list of these accounts too, but... 
<img width="441" alt="image" src="https://user-images.githubusercontent.com/639012/102576796-5be12880-40ab-11eb-84cc-ea100a8640db.png">
