### ISSUE TITLE
Possible missing FEC code for Senator Pete Ricketts

### ISSUE THREAD

**Issue by spenser-brinkman** [unitedstates/congress-legislators#918]
legislators-current.yaml correctly lists `S6NE00129` as an FEC code for Pete Ricketts, but a separate data vendor partnered with my organization also lists `S4NE00173` as an FEC code of Sen. Ricketts. The vendor's rep states that `S6NE00129` is for the 2026 election, whereas `S4NE00173` is for the upcoming 2024 election.

I'm leaning towards thinking that they are mistaken, but before I go back and tell our paid partner that they are wrong, I want to first check with the contributors here to verify what I am being told and to see if the "missing" FEC code can be added to the API here.

**Comment by JoshData** [comment]
The FEC does assign multiple IDs to candidates. This always happens if they run for House, Senate, or the President - they get an ID that starts with H, S, and P, I think. Having two IDs that start with the same letter is... unusual? unprecedented?

The source of truth here is FEC.gov. While the first ID resolves to a person and lists 2024 election info:

https://www.fec.gov/data/candidate/S6NE00129/?tab=about-candidate

the second ID does not:

https://www.fec.gov/data/candidate/S4NE00173/

It is possible the FEC assigned a new ID mistakenly and then purged it.

**Comment by spenser-brinkman** [comment]
Understood, thanks for the insight!
